// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoXjgXS4sgeR1WEBpWAX7cbjD9QFyJTNs',
    appId: '1:676224114514:web:29f2571d55cf61fd30248b',
    messagingSenderId: '676224114514',
    projectId: 'quickmedcare',
    authDomain: 'quickmedcare.firebaseapp.com',
    storageBucket: 'quickmedcare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdoTcPSghvu6PVl8faoIClTBEiSqFTLw',
    appId: '1:676224114514:android:8e57bd6f8885f6f530248b',
    messagingSenderId: '676224114514',
    projectId: 'quickmedcare',
    storageBucket: 'quickmedcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhe6aTRooxHCw59pQs75ugT1t-CMiF3kU',
    appId: '1:676224114514:ios:4d31fdca695d5fbf30248b',
    messagingSenderId: '676224114514',
    projectId: 'quickmedcare',
    storageBucket: 'quickmedcare.appspot.com',
    iosClientId: '676224114514-hr84u9tlsmnki6kr6ft31brcbqi40mmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMedcare',
  );
}
