// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4_m1DsijaUU9YMIYopAMuTAfzw6JwOBo',
    appId: '1:1091936495961:web:6bba3aa9d73466383e4448',
    messagingSenderId: '1091936495961',
    projectId: 'quick-medcare1234',
    authDomain: 'quick-medcare1234.firebaseapp.com',
    storageBucket: 'quick-medcare1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGkEy_rn9BMtOuJKJICKuZxR2k8QEeKE',
    appId: '1:1091936495961:android:66f5d4e1df571e903e4448',
    messagingSenderId: '1091936495961',
    projectId: 'quick-medcare1234',
    storageBucket: 'quick-medcare1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjI0yRa8TB7TY-seV7rxdxfrZ-MMv2PiY',
    appId: '1:1091936495961:ios:428e6f290977a5aa3e4448',
    messagingSenderId: '1091936495961',
    projectId: 'quick-medcare1234',
    storageBucket: 'quick-medcare1234.appspot.com',
    iosClientId: '1091936495961-l5ars9mo393qomttbdufcqu4jpjfmhm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMedcare',
  );
}
